# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_choice_choice_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_type',
        ),
        migrations.AddField(
            model_name='question',
            name='choice_type',
            field=models.CharField(choices=[(b'SINGLE', b'Single'), (b'MULTIPLE', b'Multiple'), (b'OPEN', b'Open')], default=b'S', max_length=8),
        ),
    ]
