# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 21:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0004_auto_20160808_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ask',
            field=models.ManyToManyField(related_name='_question_ask_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
