# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160807_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_type',
            field=models.CharField(choices=[(b'SINGLE', b'Single'), (b'MULTIPLE', b'Multiple'), (b'OPEN', b'Open')], default=b's', max_length=1),
        ),
    ]
