# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 21:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_question_ask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ask',
            field=models.ManyToManyField(related_name='tags', related_query_name='tag', to=settings.AUTH_USER_MODEL),
        ),
    ]
