# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 22:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0008_auto_20160812_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ask',
        ),
        migrations.AddField(
            model_name='question',
            name='ask',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
