# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20160813_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='expiration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
