# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20160817_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='expiration',
        ),
    ]
